excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  - Source/*/ExcludedFile.swift # Exclude files with a wildcard
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 140
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
