# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChuckNorrisRxSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChuckNorrisRxSwift
  pod 'SwiftLint'
  pod 'RxSwift', '~> 5'

  target 'ChuckNorrisRxSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChuckNorrisRxSwiftUITests' do
    # Pods for testing
  end

end
