# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChuckConsumer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChuckConsumer
  pod 'SwiftLint'

  target 'ChuckConsumerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChuckConsumerUITests' do
    # Pods for testing
  end

end
